* Possible Applications of a Zettle-Wiki:
- Wiki or full length linear articles
- Micro articles for hyperspecific topics (single molecules, parameter changes to algorithms)
- Documentation of negative results or iterative work
- Flashcards: Math problems, vocabulary, etc
- Hosting technical documentation, allowing for external commentary/examples or even a direct stack overflow Q/A type of troubleshooting of syntax
- A class can host their weekly assignments, where students generate commentary/summarization of specific content within a paper, discussion and critique of papers are allowed
* Possible Note Descriptions
** Reference Notes
- *Meta-article Title*
- *Author(s)*
- *note title/subsection*
- *Content: Markdown-like with hyperlinks to other notes and external references*
- *tags (previous specification)*
- *internal references: note id's extracted from content*
- *external references: DOI, URL or other external content link.*
- internal reference location: use #pf for paragraph, #pg for page, #s for sentence
- internal/external reference locations:
  + References can indicate roughly the location in a reference that a statement is drawn from. Narrowed down to numbered paragraphs or sentences
  + example: (#pg, 3) //page 3
             (#pg, 3, 7) ///pages 3 - 7
             (#pg, 3, (#pf, 2, (#s, 3)), 4, (#pf, 2, (#s, 1)) ) //// (page 3, paragraph 2, sentence  3) to (page 4, paragraph 2, sentence 1] ///Modify this to reduce complexity or if there are better formats
           
   + Aids in efficiently navigating ideas whether the reference is to another. Combats the "read this full book or paper to understand the idea" way of referencing other content which is prominentently used.
- direct links: links to other notes of relevance (may be redundant given tags)
- before/after link: For notes that construct a linear article. Tuple containing the subsection before and after the current note
** Commentary Note
- Reference Note ID
- content: Markdown-like with hyperlinks
- disagree-agree spectrum: (0-5 stars or 0%-100%)
- location_id: points to specific section within other note similar to above reference spec
** Question Note
- Reference Note ID
- Content: Question/clarification of interest
  - Question location within note (either full id or another location ID)
  
** Reference Literature Note
- Title
- Author(s)
- DOI, URL or any other type of atomic external link
- Date of content publication
  + allows commentary on external content such as a paper, blog, or podcast. 
** Bounty Note
- Describe what you'd like to have explained: topics, questions, explanations etc.
- bounty given

* Relay/Client Philosophy
- Host content you care about, don't connect to content you don't care for.
- A group can host their content on their relay with exclusive write access while commentary can exist on other relays.
- Aggregated relays can will compose a collective network of literature that the user is interested in, where content is easily navigable.
